"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const userController_1 = __importDefault(require("../controller/userController"));
const router = express_1.default.Router();
router.post("/signup", userController_1.default.createUser);
router.post("/signin", userController_1.default.signInUser);
router.get("/students", userController_1.default.getAllStudents);
router.post("/dorm", userController_1.default.createDorm);
router.get("/dorms/:adminId", userController_1.default.getDormsByAdminId);
router.patch("/dorm/:dormId", userController_1.default.updateDorm);
router.delete("/dorm/:dormId", userController_1.default.deleteDormById);
router.get("/dorm/:dormId", userController_1.default.getDormById);
router.get("/students/total", userController_1.default.getAllStudentsTotal);
router.get("/dorms/total/:adminId", userController_1.default.getTotalDormsAndRooms);
router.get("/:userId", userController_1.default.getUserById);
router.get("/dorms/student", userController_1.default.getAllDormsForStudentView);
router.post("/application", userController_1.default.requestRoomApplication);
router.get("/applications/:userId", userController_1.default.getAllApplicationsById);
router.patch("/application/:applicationId", userController_1.default.updateApplicationStatus);
router.patch("/application/interview/:applicationId", userController_1.default.scheduleInterviewApplication);
router.get("/applications/pendings/:adminId", userController_1.default.getAllPendingApplicationsTotal);
router.post("/notice-payment", userController_1.default.sendNoticePaymentForStudent);
router.get("/notice-payments/:userId", userController_1.default.getMyAllNoticePayments);
router.patch("/update-status-payment/:noticeId", userController_1.default.updateStatusOfNoticePayment);
router.delete("/delete-application/:applicationId", userController_1.default.deleteApplication);
router.post("/eviction-notice", userController_1.default.sendStudentEvictionNotice);
router.delete("/delete-student/:userId", userController_1.default.deleteStudentById);
/* router.patch("/undo-eviction/:userId", userController.undoEviction);
 */
router.patch("/update-application-data/:applicationId", userController_1.default.updateApplicationDataWithInterviewScoring);
exports.default = router;
